// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/miebyte/authkit/mysql/models"
)

func newBinding(db *gorm.DB, opts ...gen.DOOption) binding {
	_binding := binding{}

	_binding.bindingDo.UseDB(db, opts...)
	_binding.bindingDo.UseModel(&models.Binding{})

	tableName := _binding.bindingDo.TableName()
	_binding.ALL = field.NewAsterisk(tableName)
	_binding.Method = field.NewString(tableName, "method")
	_binding.Identifier = field.NewString(tableName, "identifier")
	_binding.AccountID = field.NewString(tableName, "account_id")

	_binding.fillFieldMap()

	return _binding
}

type binding struct {
	bindingDo bindingDo

	ALL        field.Asterisk
	Method     field.String
	Identifier field.String
	AccountID  field.String

	fieldMap map[string]field.Expr
}

func (b binding) Table(newTableName string) *binding {
	b.bindingDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b binding) As(alias string) *binding {
	b.bindingDo.DO = *(b.bindingDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *binding) updateTableName(table string) *binding {
	b.ALL = field.NewAsterisk(table)
	b.Method = field.NewString(table, "method")
	b.Identifier = field.NewString(table, "identifier")
	b.AccountID = field.NewString(table, "account_id")

	b.fillFieldMap()

	return b
}

func (b *binding) WithContext(ctx context.Context) IBindingDo { return b.bindingDo.WithContext(ctx) }

func (b binding) TableName() string { return b.bindingDo.TableName() }

func (b binding) Alias() string { return b.bindingDo.Alias() }

func (b binding) Columns(cols ...field.Expr) gen.Columns { return b.bindingDo.Columns(cols...) }

func (b *binding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *binding) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 3)
	b.fieldMap["method"] = b.Method
	b.fieldMap["identifier"] = b.Identifier
	b.fieldMap["account_id"] = b.AccountID
}

func (b binding) clone(db *gorm.DB) binding {
	b.bindingDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b binding) replaceDB(db *gorm.DB) binding {
	b.bindingDo.ReplaceDB(db)
	return b
}

type bindingDo struct{ gen.DO }

type IBindingDo interface {
	gen.SubQuery
	Debug() IBindingDo
	WithContext(ctx context.Context) IBindingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBindingDo
	WriteDB() IBindingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBindingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBindingDo
	Not(conds ...gen.Condition) IBindingDo
	Or(conds ...gen.Condition) IBindingDo
	Select(conds ...field.Expr) IBindingDo
	Where(conds ...gen.Condition) IBindingDo
	Order(conds ...field.Expr) IBindingDo
	Distinct(cols ...field.Expr) IBindingDo
	Omit(cols ...field.Expr) IBindingDo
	Join(table schema.Tabler, on ...field.Expr) IBindingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBindingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBindingDo
	Group(cols ...field.Expr) IBindingDo
	Having(conds ...gen.Condition) IBindingDo
	Limit(limit int) IBindingDo
	Offset(offset int) IBindingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBindingDo
	Unscoped() IBindingDo
	Create(values ...*models.Binding) error
	CreateInBatches(values []*models.Binding, batchSize int) error
	Save(values ...*models.Binding) error
	First() (*models.Binding, error)
	Take() (*models.Binding, error)
	Last() (*models.Binding, error)
	Find() ([]*models.Binding, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Binding, err error)
	FindInBatches(result *[]*models.Binding, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Binding) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBindingDo
	Assign(attrs ...field.AssignExpr) IBindingDo
	Joins(fields ...field.RelationField) IBindingDo
	Preload(fields ...field.RelationField) IBindingDo
	FirstOrInit() (*models.Binding, error)
	FirstOrCreate() (*models.Binding, error)
	FindByPage(offset int, limit int) (result []*models.Binding, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBindingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bindingDo) Debug() IBindingDo {
	return b.withDO(b.DO.Debug())
}

func (b bindingDo) WithContext(ctx context.Context) IBindingDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bindingDo) ReadDB() IBindingDo {
	return b.Clauses(dbresolver.Read)
}

func (b bindingDo) WriteDB() IBindingDo {
	return b.Clauses(dbresolver.Write)
}

func (b bindingDo) Session(config *gorm.Session) IBindingDo {
	return b.withDO(b.DO.Session(config))
}

func (b bindingDo) Clauses(conds ...clause.Expression) IBindingDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bindingDo) Returning(value interface{}, columns ...string) IBindingDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bindingDo) Not(conds ...gen.Condition) IBindingDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bindingDo) Or(conds ...gen.Condition) IBindingDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bindingDo) Select(conds ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bindingDo) Where(conds ...gen.Condition) IBindingDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bindingDo) Order(conds ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bindingDo) Distinct(cols ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bindingDo) Omit(cols ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bindingDo) Join(table schema.Tabler, on ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bindingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBindingDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bindingDo) RightJoin(table schema.Tabler, on ...field.Expr) IBindingDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bindingDo) Group(cols ...field.Expr) IBindingDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bindingDo) Having(conds ...gen.Condition) IBindingDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bindingDo) Limit(limit int) IBindingDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bindingDo) Offset(offset int) IBindingDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bindingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBindingDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bindingDo) Unscoped() IBindingDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bindingDo) Create(values ...*models.Binding) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bindingDo) CreateInBatches(values []*models.Binding, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bindingDo) Save(values ...*models.Binding) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bindingDo) First() (*models.Binding, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Binding), nil
	}
}

func (b bindingDo) Take() (*models.Binding, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Binding), nil
	}
}

func (b bindingDo) Last() (*models.Binding, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Binding), nil
	}
}

func (b bindingDo) Find() ([]*models.Binding, error) {
	result, err := b.DO.Find()
	return result.([]*models.Binding), err
}

func (b bindingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Binding, err error) {
	buf := make([]*models.Binding, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bindingDo) FindInBatches(result *[]*models.Binding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bindingDo) Attrs(attrs ...field.AssignExpr) IBindingDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bindingDo) Assign(attrs ...field.AssignExpr) IBindingDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bindingDo) Joins(fields ...field.RelationField) IBindingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bindingDo) Preload(fields ...field.RelationField) IBindingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bindingDo) FirstOrInit() (*models.Binding, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Binding), nil
	}
}

func (b bindingDo) FirstOrCreate() (*models.Binding, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Binding), nil
	}
}

func (b bindingDo) FindByPage(offset int, limit int) (result []*models.Binding, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bindingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bindingDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bindingDo) Delete(models ...*models.Binding) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bindingDo) withDO(do gen.Dao) *bindingDo {
	b.DO = *do.(*gen.DO)
	return b
}
