// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Challenge:          newChallenge(db, opts...),
		Claim:              newClaim(db, opts...),
		CommentIdempotency: newCommentIdempotency(db, opts...),
		Game:               newGame(db, opts...),
		GameWish:           newGameWish(db, opts...),
		Group:              newGroup(db, opts...),
		Idempotency:        newIdempotency(db, opts...),
		Invite:             newInvite(db, opts...),
		Member:             newMember(db, opts...),
		Notification:       newNotification(db, opts...),
		Photo:              newPhoto(db, opts...),
		Player:             newPlayer(db, opts...),
		Rate:               newRate(db, opts...),
		Round:              newRound(db, opts...),
		RoundComment:       newRoundComment(db, opts...),
		RoundShare:         newRoundShare(db, opts...),
		Session:            newSession(db, opts...),
		Trial:              newTrial(db, opts...),
		User:               newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Challenge          challenge
	Claim              claim
	CommentIdempotency commentIdempotency
	Game               game
	GameWish           gameWish
	Group              group
	Idempotency        idempotency
	Invite             invite
	Member             member
	Notification       notification
	Photo              photo
	Player             player
	Rate               rate
	Round              round
	RoundComment       roundComment
	RoundShare         roundShare
	Session            session
	Trial              trial
	User               user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Challenge:          q.Challenge.clone(db),
		Claim:              q.Claim.clone(db),
		CommentIdempotency: q.CommentIdempotency.clone(db),
		Game:               q.Game.clone(db),
		GameWish:           q.GameWish.clone(db),
		Group:              q.Group.clone(db),
		Idempotency:        q.Idempotency.clone(db),
		Invite:             q.Invite.clone(db),
		Member:             q.Member.clone(db),
		Notification:       q.Notification.clone(db),
		Photo:              q.Photo.clone(db),
		Player:             q.Player.clone(db),
		Rate:               q.Rate.clone(db),
		Round:              q.Round.clone(db),
		RoundComment:       q.RoundComment.clone(db),
		RoundShare:         q.RoundShare.clone(db),
		Session:            q.Session.clone(db),
		Trial:              q.Trial.clone(db),
		User:               q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Challenge:          q.Challenge.replaceDB(db),
		Claim:              q.Claim.replaceDB(db),
		CommentIdempotency: q.CommentIdempotency.replaceDB(db),
		Game:               q.Game.replaceDB(db),
		GameWish:           q.GameWish.replaceDB(db),
		Group:              q.Group.replaceDB(db),
		Idempotency:        q.Idempotency.replaceDB(db),
		Invite:             q.Invite.replaceDB(db),
		Member:             q.Member.replaceDB(db),
		Notification:       q.Notification.replaceDB(db),
		Photo:              q.Photo.replaceDB(db),
		Player:             q.Player.replaceDB(db),
		Rate:               q.Rate.replaceDB(db),
		Round:              q.Round.replaceDB(db),
		RoundComment:       q.RoundComment.replaceDB(db),
		RoundShare:         q.RoundShare.replaceDB(db),
		Session:            q.Session.replaceDB(db),
		Trial:              q.Trial.replaceDB(db),
		User:               q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Challenge          IChallengeDo
	Claim              IClaimDo
	CommentIdempotency ICommentIdempotencyDo
	Game               IGameDo
	GameWish           IGameWishDo
	Group              IGroupDo
	Idempotency        IIdempotencyDo
	Invite             IInviteDo
	Member             IMemberDo
	Notification       INotificationDo
	Photo              IPhotoDo
	Player             IPlayerDo
	Rate               IRateDo
	Round              IRoundDo
	RoundComment       IRoundCommentDo
	RoundShare         IRoundShareDo
	Session            ISessionDo
	Trial              ITrialDo
	User               IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Challenge:          q.Challenge.WithContext(ctx),
		Claim:              q.Claim.WithContext(ctx),
		CommentIdempotency: q.CommentIdempotency.WithContext(ctx),
		Game:               q.Game.WithContext(ctx),
		GameWish:           q.GameWish.WithContext(ctx),
		Group:              q.Group.WithContext(ctx),
		Idempotency:        q.Idempotency.WithContext(ctx),
		Invite:             q.Invite.WithContext(ctx),
		Member:             q.Member.WithContext(ctx),
		Notification:       q.Notification.WithContext(ctx),
		Photo:              q.Photo.WithContext(ctx),
		Player:             q.Player.WithContext(ctx),
		Rate:               q.Rate.WithContext(ctx),
		Round:              q.Round.WithContext(ctx),
		RoundComment:       q.RoundComment.WithContext(ctx),
		RoundShare:         q.RoundShare.WithContext(ctx),
		Session:            q.Session.WithContext(ctx),
		Trial:              q.Trial.WithContext(ctx),
		User:               q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
