// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newIdempotency(db *gorm.DB, opts ...gen.DOOption) idempotency {
	_idempotency := idempotency{}

	_idempotency.idempotencyDo.UseDB(db, opts...)
	_idempotency.idempotencyDo.UseModel(&models.Idempotency{})

	tableName := _idempotency.idempotencyDo.TableName()
	_idempotency.ALL = field.NewAsterisk(tableName)
	_idempotency.GroupID = field.NewString(tableName, "group_id")
	_idempotency.UserID = field.NewString(tableName, "user_id")
	_idempotency.RequestKey = field.NewString(tableName, "request_key")
	_idempotency.Hash = field.NewString(tableName, "hash")
	_idempotency.RoundID = field.NewString(tableName, "round_id")

	_idempotency.fillFieldMap()

	return _idempotency
}

type idempotency struct {
	idempotencyDo idempotencyDo

	ALL        field.Asterisk
	GroupID    field.String
	UserID     field.String
	RequestKey field.String
	Hash       field.String
	RoundID    field.String

	fieldMap map[string]field.Expr
}

func (i idempotency) Table(newTableName string) *idempotency {
	i.idempotencyDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i idempotency) As(alias string) *idempotency {
	i.idempotencyDo.DO = *(i.idempotencyDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *idempotency) updateTableName(table string) *idempotency {
	i.ALL = field.NewAsterisk(table)
	i.GroupID = field.NewString(table, "group_id")
	i.UserID = field.NewString(table, "user_id")
	i.RequestKey = field.NewString(table, "request_key")
	i.Hash = field.NewString(table, "hash")
	i.RoundID = field.NewString(table, "round_id")

	i.fillFieldMap()

	return i
}

func (i *idempotency) WithContext(ctx context.Context) IIdempotencyDo {
	return i.idempotencyDo.WithContext(ctx)
}

func (i idempotency) TableName() string { return i.idempotencyDo.TableName() }

func (i idempotency) Alias() string { return i.idempotencyDo.Alias() }

func (i idempotency) Columns(cols ...field.Expr) gen.Columns { return i.idempotencyDo.Columns(cols...) }

func (i *idempotency) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *idempotency) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["group_id"] = i.GroupID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["request_key"] = i.RequestKey
	i.fieldMap["hash"] = i.Hash
	i.fieldMap["round_id"] = i.RoundID
}

func (i idempotency) clone(db *gorm.DB) idempotency {
	i.idempotencyDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i idempotency) replaceDB(db *gorm.DB) idempotency {
	i.idempotencyDo.ReplaceDB(db)
	return i
}

type idempotencyDo struct{ gen.DO }

type IIdempotencyDo interface {
	gen.SubQuery
	Debug() IIdempotencyDo
	WithContext(ctx context.Context) IIdempotencyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIdempotencyDo
	WriteDB() IIdempotencyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIdempotencyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIdempotencyDo
	Not(conds ...gen.Condition) IIdempotencyDo
	Or(conds ...gen.Condition) IIdempotencyDo
	Select(conds ...field.Expr) IIdempotencyDo
	Where(conds ...gen.Condition) IIdempotencyDo
	Order(conds ...field.Expr) IIdempotencyDo
	Distinct(cols ...field.Expr) IIdempotencyDo
	Omit(cols ...field.Expr) IIdempotencyDo
	Join(table schema.Tabler, on ...field.Expr) IIdempotencyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyDo
	Group(cols ...field.Expr) IIdempotencyDo
	Having(conds ...gen.Condition) IIdempotencyDo
	Limit(limit int) IIdempotencyDo
	Offset(offset int) IIdempotencyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyDo
	Unscoped() IIdempotencyDo
	Create(values ...*models.Idempotency) error
	CreateInBatches(values []*models.Idempotency, batchSize int) error
	Save(values ...*models.Idempotency) error
	First() (*models.Idempotency, error)
	Take() (*models.Idempotency, error)
	Last() (*models.Idempotency, error)
	Find() ([]*models.Idempotency, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Idempotency, err error)
	FindInBatches(result *[]*models.Idempotency, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Idempotency) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIdempotencyDo
	Assign(attrs ...field.AssignExpr) IIdempotencyDo
	Joins(fields ...field.RelationField) IIdempotencyDo
	Preload(fields ...field.RelationField) IIdempotencyDo
	FirstOrInit() (*models.Idempotency, error)
	FirstOrCreate() (*models.Idempotency, error)
	FindByPage(offset int, limit int) (result []*models.Idempotency, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIdempotencyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i idempotencyDo) Debug() IIdempotencyDo {
	return i.withDO(i.DO.Debug())
}

func (i idempotencyDo) WithContext(ctx context.Context) IIdempotencyDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i idempotencyDo) ReadDB() IIdempotencyDo {
	return i.Clauses(dbresolver.Read)
}

func (i idempotencyDo) WriteDB() IIdempotencyDo {
	return i.Clauses(dbresolver.Write)
}

func (i idempotencyDo) Session(config *gorm.Session) IIdempotencyDo {
	return i.withDO(i.DO.Session(config))
}

func (i idempotencyDo) Clauses(conds ...clause.Expression) IIdempotencyDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i idempotencyDo) Returning(value interface{}, columns ...string) IIdempotencyDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i idempotencyDo) Not(conds ...gen.Condition) IIdempotencyDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i idempotencyDo) Or(conds ...gen.Condition) IIdempotencyDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i idempotencyDo) Select(conds ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i idempotencyDo) Where(conds ...gen.Condition) IIdempotencyDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i idempotencyDo) Order(conds ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i idempotencyDo) Distinct(cols ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i idempotencyDo) Omit(cols ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i idempotencyDo) Join(table schema.Tabler, on ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i idempotencyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i idempotencyDo) RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i idempotencyDo) Group(cols ...field.Expr) IIdempotencyDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i idempotencyDo) Having(conds ...gen.Condition) IIdempotencyDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i idempotencyDo) Limit(limit int) IIdempotencyDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i idempotencyDo) Offset(offset int) IIdempotencyDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i idempotencyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i idempotencyDo) Unscoped() IIdempotencyDo {
	return i.withDO(i.DO.Unscoped())
}

func (i idempotencyDo) Create(values ...*models.Idempotency) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i idempotencyDo) CreateInBatches(values []*models.Idempotency, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i idempotencyDo) Save(values ...*models.Idempotency) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i idempotencyDo) First() (*models.Idempotency, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Idempotency), nil
	}
}

func (i idempotencyDo) Take() (*models.Idempotency, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Idempotency), nil
	}
}

func (i idempotencyDo) Last() (*models.Idempotency, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Idempotency), nil
	}
}

func (i idempotencyDo) Find() ([]*models.Idempotency, error) {
	result, err := i.DO.Find()
	return result.([]*models.Idempotency), err
}

func (i idempotencyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Idempotency, err error) {
	buf := make([]*models.Idempotency, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i idempotencyDo) FindInBatches(result *[]*models.Idempotency, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i idempotencyDo) Attrs(attrs ...field.AssignExpr) IIdempotencyDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i idempotencyDo) Assign(attrs ...field.AssignExpr) IIdempotencyDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i idempotencyDo) Joins(fields ...field.RelationField) IIdempotencyDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i idempotencyDo) Preload(fields ...field.RelationField) IIdempotencyDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i idempotencyDo) FirstOrInit() (*models.Idempotency, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Idempotency), nil
	}
}

func (i idempotencyDo) FirstOrCreate() (*models.Idempotency, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Idempotency), nil
	}
}

func (i idempotencyDo) FindByPage(offset int, limit int) (result []*models.Idempotency, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i idempotencyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i idempotencyDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i idempotencyDo) Delete(models ...*models.Idempotency) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *idempotencyDo) withDO(do gen.Dao) *idempotencyDo {
	i.DO = *do.(*gen.DO)
	return i
}
