// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newRate(db *gorm.DB, opts ...gen.DOOption) rate {
	_rate := rate{}

	_rate.rateDo.UseDB(db, opts...)
	_rate.rateDo.UseModel(&models.Rate{})

	tableName := _rate.rateDo.TableName()
	_rate.ALL = field.NewAsterisk(tableName)
	_rate.ID = field.NewString(tableName, "id")
	_rate.Starts = field.NewTime(tableName, "starts")
	_rate.Hits = field.NewInt(tableName, "count")

	_rate.fillFieldMap()

	return _rate
}

type rate struct {
	rateDo rateDo

	ALL    field.Asterisk
	ID     field.String
	Starts field.Time
	Hits   field.Int

	fieldMap map[string]field.Expr
}

func (r rate) Table(newTableName string) *rate {
	r.rateDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rate) As(alias string) *rate {
	r.rateDo.DO = *(r.rateDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rate) updateTableName(table string) *rate {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.Starts = field.NewTime(table, "starts")
	r.Hits = field.NewInt(table, "count")

	r.fillFieldMap()

	return r
}

func (r *rate) WithContext(ctx context.Context) IRateDo { return r.rateDo.WithContext(ctx) }

func (r rate) TableName() string { return r.rateDo.TableName() }

func (r rate) Alias() string { return r.rateDo.Alias() }

func (r rate) Columns(cols ...field.Expr) gen.Columns { return r.rateDo.Columns(cols...) }

func (r *rate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rate) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["id"] = r.ID
	r.fieldMap["starts"] = r.Starts
	r.fieldMap["count"] = r.Hits
}

func (r rate) clone(db *gorm.DB) rate {
	r.rateDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rate) replaceDB(db *gorm.DB) rate {
	r.rateDo.ReplaceDB(db)
	return r
}

type rateDo struct{ gen.DO }

type IRateDo interface {
	gen.SubQuery
	Debug() IRateDo
	WithContext(ctx context.Context) IRateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRateDo
	WriteDB() IRateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRateDo
	Not(conds ...gen.Condition) IRateDo
	Or(conds ...gen.Condition) IRateDo
	Select(conds ...field.Expr) IRateDo
	Where(conds ...gen.Condition) IRateDo
	Order(conds ...field.Expr) IRateDo
	Distinct(cols ...field.Expr) IRateDo
	Omit(cols ...field.Expr) IRateDo
	Join(table schema.Tabler, on ...field.Expr) IRateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRateDo
	Group(cols ...field.Expr) IRateDo
	Having(conds ...gen.Condition) IRateDo
	Limit(limit int) IRateDo
	Offset(offset int) IRateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRateDo
	Unscoped() IRateDo
	Create(values ...*models.Rate) error
	CreateInBatches(values []*models.Rate, batchSize int) error
	Save(values ...*models.Rate) error
	First() (*models.Rate, error)
	Take() (*models.Rate, error)
	Last() (*models.Rate, error)
	Find() ([]*models.Rate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Rate, err error)
	FindInBatches(result *[]*models.Rate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Rate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRateDo
	Assign(attrs ...field.AssignExpr) IRateDo
	Joins(fields ...field.RelationField) IRateDo
	Preload(fields ...field.RelationField) IRateDo
	FirstOrInit() (*models.Rate, error)
	FirstOrCreate() (*models.Rate, error)
	FindByPage(offset int, limit int) (result []*models.Rate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rateDo) Debug() IRateDo {
	return r.withDO(r.DO.Debug())
}

func (r rateDo) WithContext(ctx context.Context) IRateDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rateDo) ReadDB() IRateDo {
	return r.Clauses(dbresolver.Read)
}

func (r rateDo) WriteDB() IRateDo {
	return r.Clauses(dbresolver.Write)
}

func (r rateDo) Session(config *gorm.Session) IRateDo {
	return r.withDO(r.DO.Session(config))
}

func (r rateDo) Clauses(conds ...clause.Expression) IRateDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rateDo) Returning(value interface{}, columns ...string) IRateDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rateDo) Not(conds ...gen.Condition) IRateDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rateDo) Or(conds ...gen.Condition) IRateDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rateDo) Select(conds ...field.Expr) IRateDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rateDo) Where(conds ...gen.Condition) IRateDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rateDo) Order(conds ...field.Expr) IRateDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rateDo) Distinct(cols ...field.Expr) IRateDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rateDo) Omit(cols ...field.Expr) IRateDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rateDo) Join(table schema.Tabler, on ...field.Expr) IRateDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRateDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rateDo) RightJoin(table schema.Tabler, on ...field.Expr) IRateDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rateDo) Group(cols ...field.Expr) IRateDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rateDo) Having(conds ...gen.Condition) IRateDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rateDo) Limit(limit int) IRateDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rateDo) Offset(offset int) IRateDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRateDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rateDo) Unscoped() IRateDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rateDo) Create(values ...*models.Rate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rateDo) CreateInBatches(values []*models.Rate, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rateDo) Save(values ...*models.Rate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rateDo) First() (*models.Rate, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Rate), nil
	}
}

func (r rateDo) Take() (*models.Rate, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Rate), nil
	}
}

func (r rateDo) Last() (*models.Rate, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Rate), nil
	}
}

func (r rateDo) Find() ([]*models.Rate, error) {
	result, err := r.DO.Find()
	return result.([]*models.Rate), err
}

func (r rateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Rate, err error) {
	buf := make([]*models.Rate, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rateDo) FindInBatches(result *[]*models.Rate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rateDo) Attrs(attrs ...field.AssignExpr) IRateDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rateDo) Assign(attrs ...field.AssignExpr) IRateDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rateDo) Joins(fields ...field.RelationField) IRateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rateDo) Preload(fields ...field.RelationField) IRateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rateDo) FirstOrInit() (*models.Rate, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Rate), nil
	}
}

func (r rateDo) FirstOrCreate() (*models.Rate, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Rate), nil
	}
}

func (r rateDo) FindByPage(offset int, limit int) (result []*models.Rate, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rateDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rateDo) Delete(models ...*models.Rate) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rateDo) withDO(do gen.Dao) *rateDo {
	r.DO = *do.(*gen.DO)
	return r
}
