// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newChallenge(db *gorm.DB, opts ...gen.DOOption) challenge {
	_challenge := challenge{}

	_challenge.challengeDo.UseDB(db, opts...)
	_challenge.challengeDo.UseModel(&models.Challenge{})

	tableName := _challenge.challengeDo.TableName()
	_challenge.ALL = field.NewAsterisk(tableName)
	_challenge.Email = field.NewString(tableName, "email")
	_challenge.Hash = field.NewString(tableName, "hash")
	_challenge.InviteHash = field.NewString(tableName, "invite_hash")
	_challenge.Expires = field.NewTime(tableName, "expires")
	_challenge.Sent = field.NewTime(tableName, "sent")
	_challenge.Attempts = field.NewInt(tableName, "attempts")
	_challenge.Ready = field.NewBool(tableName, "ready")

	_challenge.fillFieldMap()

	return _challenge
}

type challenge struct {
	challengeDo challengeDo

	ALL        field.Asterisk
	Email      field.String
	Hash       field.String
	InviteHash field.String
	Expires    field.Time
	Sent       field.Time
	Attempts   field.Int
	Ready      field.Bool

	fieldMap map[string]field.Expr
}

func (c challenge) Table(newTableName string) *challenge {
	c.challengeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c challenge) As(alias string) *challenge {
	c.challengeDo.DO = *(c.challengeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *challenge) updateTableName(table string) *challenge {
	c.ALL = field.NewAsterisk(table)
	c.Email = field.NewString(table, "email")
	c.Hash = field.NewString(table, "hash")
	c.InviteHash = field.NewString(table, "invite_hash")
	c.Expires = field.NewTime(table, "expires")
	c.Sent = field.NewTime(table, "sent")
	c.Attempts = field.NewInt(table, "attempts")
	c.Ready = field.NewBool(table, "ready")

	c.fillFieldMap()

	return c
}

func (c *challenge) WithContext(ctx context.Context) IChallengeDo {
	return c.challengeDo.WithContext(ctx)
}

func (c challenge) TableName() string { return c.challengeDo.TableName() }

func (c challenge) Alias() string { return c.challengeDo.Alias() }

func (c challenge) Columns(cols ...field.Expr) gen.Columns { return c.challengeDo.Columns(cols...) }

func (c *challenge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *challenge) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["email"] = c.Email
	c.fieldMap["hash"] = c.Hash
	c.fieldMap["invite_hash"] = c.InviteHash
	c.fieldMap["expires"] = c.Expires
	c.fieldMap["sent"] = c.Sent
	c.fieldMap["attempts"] = c.Attempts
	c.fieldMap["ready"] = c.Ready
}

func (c challenge) clone(db *gorm.DB) challenge {
	c.challengeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c challenge) replaceDB(db *gorm.DB) challenge {
	c.challengeDo.ReplaceDB(db)
	return c
}

type challengeDo struct{ gen.DO }

type IChallengeDo interface {
	gen.SubQuery
	Debug() IChallengeDo
	WithContext(ctx context.Context) IChallengeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChallengeDo
	WriteDB() IChallengeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChallengeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChallengeDo
	Not(conds ...gen.Condition) IChallengeDo
	Or(conds ...gen.Condition) IChallengeDo
	Select(conds ...field.Expr) IChallengeDo
	Where(conds ...gen.Condition) IChallengeDo
	Order(conds ...field.Expr) IChallengeDo
	Distinct(cols ...field.Expr) IChallengeDo
	Omit(cols ...field.Expr) IChallengeDo
	Join(table schema.Tabler, on ...field.Expr) IChallengeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChallengeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChallengeDo
	Group(cols ...field.Expr) IChallengeDo
	Having(conds ...gen.Condition) IChallengeDo
	Limit(limit int) IChallengeDo
	Offset(offset int) IChallengeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChallengeDo
	Unscoped() IChallengeDo
	Create(values ...*models.Challenge) error
	CreateInBatches(values []*models.Challenge, batchSize int) error
	Save(values ...*models.Challenge) error
	First() (*models.Challenge, error)
	Take() (*models.Challenge, error)
	Last() (*models.Challenge, error)
	Find() ([]*models.Challenge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Challenge, err error)
	FindInBatches(result *[]*models.Challenge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Challenge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChallengeDo
	Assign(attrs ...field.AssignExpr) IChallengeDo
	Joins(fields ...field.RelationField) IChallengeDo
	Preload(fields ...field.RelationField) IChallengeDo
	FirstOrInit() (*models.Challenge, error)
	FirstOrCreate() (*models.Challenge, error)
	FindByPage(offset int, limit int) (result []*models.Challenge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChallengeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c challengeDo) Debug() IChallengeDo {
	return c.withDO(c.DO.Debug())
}

func (c challengeDo) WithContext(ctx context.Context) IChallengeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c challengeDo) ReadDB() IChallengeDo {
	return c.Clauses(dbresolver.Read)
}

func (c challengeDo) WriteDB() IChallengeDo {
	return c.Clauses(dbresolver.Write)
}

func (c challengeDo) Session(config *gorm.Session) IChallengeDo {
	return c.withDO(c.DO.Session(config))
}

func (c challengeDo) Clauses(conds ...clause.Expression) IChallengeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c challengeDo) Returning(value interface{}, columns ...string) IChallengeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c challengeDo) Not(conds ...gen.Condition) IChallengeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c challengeDo) Or(conds ...gen.Condition) IChallengeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c challengeDo) Select(conds ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c challengeDo) Where(conds ...gen.Condition) IChallengeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c challengeDo) Order(conds ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c challengeDo) Distinct(cols ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c challengeDo) Omit(cols ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c challengeDo) Join(table schema.Tabler, on ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c challengeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c challengeDo) RightJoin(table schema.Tabler, on ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c challengeDo) Group(cols ...field.Expr) IChallengeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c challengeDo) Having(conds ...gen.Condition) IChallengeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c challengeDo) Limit(limit int) IChallengeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c challengeDo) Offset(offset int) IChallengeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c challengeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChallengeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c challengeDo) Unscoped() IChallengeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c challengeDo) Create(values ...*models.Challenge) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c challengeDo) CreateInBatches(values []*models.Challenge, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c challengeDo) Save(values ...*models.Challenge) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c challengeDo) First() (*models.Challenge, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Challenge), nil
	}
}

func (c challengeDo) Take() (*models.Challenge, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Challenge), nil
	}
}

func (c challengeDo) Last() (*models.Challenge, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Challenge), nil
	}
}

func (c challengeDo) Find() ([]*models.Challenge, error) {
	result, err := c.DO.Find()
	return result.([]*models.Challenge), err
}

func (c challengeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Challenge, err error) {
	buf := make([]*models.Challenge, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c challengeDo) FindInBatches(result *[]*models.Challenge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c challengeDo) Attrs(attrs ...field.AssignExpr) IChallengeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c challengeDo) Assign(attrs ...field.AssignExpr) IChallengeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c challengeDo) Joins(fields ...field.RelationField) IChallengeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c challengeDo) Preload(fields ...field.RelationField) IChallengeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c challengeDo) FirstOrInit() (*models.Challenge, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Challenge), nil
	}
}

func (c challengeDo) FirstOrCreate() (*models.Challenge, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Challenge), nil
	}
}

func (c challengeDo) FindByPage(offset int, limit int) (result []*models.Challenge, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c challengeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c challengeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c challengeDo) Delete(models ...*models.Challenge) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *challengeDo) withDO(do gen.Dao) *challengeDo {
	c.DO = *do.(*gen.DO)
	return c
}
