// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newRoundComment(db *gorm.DB, opts ...gen.DOOption) roundComment {
	_roundComment := roundComment{}

	_roundComment.roundCommentDo.UseDB(db, opts...)
	_roundComment.roundCommentDo.UseModel(&models.RoundComment{})

	tableName := _roundComment.roundCommentDo.TableName()
	_roundComment.ALL = field.NewAsterisk(tableName)
	_roundComment.ID = field.NewString(tableName, "id")
	_roundComment.GroupID = field.NewString(tableName, "group_id")
	_roundComment.RoundID = field.NewString(tableName, "round_id")
	_roundComment.Author = field.NewString(tableName, "author")
	_roundComment.Body = field.NewString(tableName, "body")
	_roundComment.ParentID = field.NewString(tableName, "parent_id")
	_roundComment.Created = field.NewTime(tableName, "created")

	_roundComment.fillFieldMap()

	return _roundComment
}

type roundComment struct {
	roundCommentDo roundCommentDo

	ALL      field.Asterisk
	ID       field.String
	GroupID  field.String
	RoundID  field.String
	Author   field.String
	Body     field.String
	ParentID field.String
	Created  field.Time

	fieldMap map[string]field.Expr
}

func (r roundComment) Table(newTableName string) *roundComment {
	r.roundCommentDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roundComment) As(alias string) *roundComment {
	r.roundCommentDo.DO = *(r.roundCommentDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roundComment) updateTableName(table string) *roundComment {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.GroupID = field.NewString(table, "group_id")
	r.RoundID = field.NewString(table, "round_id")
	r.Author = field.NewString(table, "author")
	r.Body = field.NewString(table, "body")
	r.ParentID = field.NewString(table, "parent_id")
	r.Created = field.NewTime(table, "created")

	r.fillFieldMap()

	return r
}

func (r *roundComment) WithContext(ctx context.Context) IRoundCommentDo {
	return r.roundCommentDo.WithContext(ctx)
}

func (r roundComment) TableName() string { return r.roundCommentDo.TableName() }

func (r roundComment) Alias() string { return r.roundCommentDo.Alias() }

func (r roundComment) Columns(cols ...field.Expr) gen.Columns {
	return r.roundCommentDo.Columns(cols...)
}

func (r *roundComment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roundComment) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["group_id"] = r.GroupID
	r.fieldMap["round_id"] = r.RoundID
	r.fieldMap["author"] = r.Author
	r.fieldMap["body"] = r.Body
	r.fieldMap["parent_id"] = r.ParentID
	r.fieldMap["created"] = r.Created
}

func (r roundComment) clone(db *gorm.DB) roundComment {
	r.roundCommentDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roundComment) replaceDB(db *gorm.DB) roundComment {
	r.roundCommentDo.ReplaceDB(db)
	return r
}

type roundCommentDo struct{ gen.DO }

type IRoundCommentDo interface {
	gen.SubQuery
	Debug() IRoundCommentDo
	WithContext(ctx context.Context) IRoundCommentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoundCommentDo
	WriteDB() IRoundCommentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoundCommentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoundCommentDo
	Not(conds ...gen.Condition) IRoundCommentDo
	Or(conds ...gen.Condition) IRoundCommentDo
	Select(conds ...field.Expr) IRoundCommentDo
	Where(conds ...gen.Condition) IRoundCommentDo
	Order(conds ...field.Expr) IRoundCommentDo
	Distinct(cols ...field.Expr) IRoundCommentDo
	Omit(cols ...field.Expr) IRoundCommentDo
	Join(table schema.Tabler, on ...field.Expr) IRoundCommentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoundCommentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoundCommentDo
	Group(cols ...field.Expr) IRoundCommentDo
	Having(conds ...gen.Condition) IRoundCommentDo
	Limit(limit int) IRoundCommentDo
	Offset(offset int) IRoundCommentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundCommentDo
	Unscoped() IRoundCommentDo
	Create(values ...*models.RoundComment) error
	CreateInBatches(values []*models.RoundComment, batchSize int) error
	Save(values ...*models.RoundComment) error
	First() (*models.RoundComment, error)
	Take() (*models.RoundComment, error)
	Last() (*models.RoundComment, error)
	Find() ([]*models.RoundComment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RoundComment, err error)
	FindInBatches(result *[]*models.RoundComment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.RoundComment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoundCommentDo
	Assign(attrs ...field.AssignExpr) IRoundCommentDo
	Joins(fields ...field.RelationField) IRoundCommentDo
	Preload(fields ...field.RelationField) IRoundCommentDo
	FirstOrInit() (*models.RoundComment, error)
	FirstOrCreate() (*models.RoundComment, error)
	FindByPage(offset int, limit int) (result []*models.RoundComment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoundCommentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roundCommentDo) Debug() IRoundCommentDo {
	return r.withDO(r.DO.Debug())
}

func (r roundCommentDo) WithContext(ctx context.Context) IRoundCommentDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roundCommentDo) ReadDB() IRoundCommentDo {
	return r.Clauses(dbresolver.Read)
}

func (r roundCommentDo) WriteDB() IRoundCommentDo {
	return r.Clauses(dbresolver.Write)
}

func (r roundCommentDo) Session(config *gorm.Session) IRoundCommentDo {
	return r.withDO(r.DO.Session(config))
}

func (r roundCommentDo) Clauses(conds ...clause.Expression) IRoundCommentDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roundCommentDo) Returning(value interface{}, columns ...string) IRoundCommentDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roundCommentDo) Not(conds ...gen.Condition) IRoundCommentDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roundCommentDo) Or(conds ...gen.Condition) IRoundCommentDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roundCommentDo) Select(conds ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roundCommentDo) Where(conds ...gen.Condition) IRoundCommentDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roundCommentDo) Order(conds ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roundCommentDo) Distinct(cols ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roundCommentDo) Omit(cols ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roundCommentDo) Join(table schema.Tabler, on ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roundCommentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roundCommentDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roundCommentDo) Group(cols ...field.Expr) IRoundCommentDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roundCommentDo) Having(conds ...gen.Condition) IRoundCommentDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roundCommentDo) Limit(limit int) IRoundCommentDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roundCommentDo) Offset(offset int) IRoundCommentDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roundCommentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundCommentDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roundCommentDo) Unscoped() IRoundCommentDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roundCommentDo) Create(values ...*models.RoundComment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roundCommentDo) CreateInBatches(values []*models.RoundComment, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roundCommentDo) Save(values ...*models.RoundComment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roundCommentDo) First() (*models.RoundComment, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundComment), nil
	}
}

func (r roundCommentDo) Take() (*models.RoundComment, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundComment), nil
	}
}

func (r roundCommentDo) Last() (*models.RoundComment, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundComment), nil
	}
}

func (r roundCommentDo) Find() ([]*models.RoundComment, error) {
	result, err := r.DO.Find()
	return result.([]*models.RoundComment), err
}

func (r roundCommentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RoundComment, err error) {
	buf := make([]*models.RoundComment, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roundCommentDo) FindInBatches(result *[]*models.RoundComment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roundCommentDo) Attrs(attrs ...field.AssignExpr) IRoundCommentDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roundCommentDo) Assign(attrs ...field.AssignExpr) IRoundCommentDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roundCommentDo) Joins(fields ...field.RelationField) IRoundCommentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roundCommentDo) Preload(fields ...field.RelationField) IRoundCommentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roundCommentDo) FirstOrInit() (*models.RoundComment, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundComment), nil
	}
}

func (r roundCommentDo) FirstOrCreate() (*models.RoundComment, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundComment), nil
	}
}

func (r roundCommentDo) FindByPage(offset int, limit int) (result []*models.RoundComment, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roundCommentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roundCommentDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roundCommentDo) Delete(models ...*models.RoundComment) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roundCommentDo) withDO(do gen.Dao) *roundCommentDo {
	r.DO = *do.(*gen.DO)
	return r
}
