// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newCommentIdempotency(db *gorm.DB, opts ...gen.DOOption) commentIdempotency {
	_commentIdempotency := commentIdempotency{}

	_commentIdempotency.commentIdempotencyDo.UseDB(db, opts...)
	_commentIdempotency.commentIdempotencyDo.UseModel(&models.CommentIdempotency{})

	tableName := _commentIdempotency.commentIdempotencyDo.TableName()
	_commentIdempotency.ALL = field.NewAsterisk(tableName)
	_commentIdempotency.GroupID = field.NewString(tableName, "group_id")
	_commentIdempotency.UserID = field.NewString(tableName, "user_id")
	_commentIdempotency.RoundID = field.NewString(tableName, "round_id")
	_commentIdempotency.RequestKey = field.NewString(tableName, "request_key")
	_commentIdempotency.Hash = field.NewString(tableName, "hash")
	_commentIdempotency.CommentID = field.NewString(tableName, "comment_id")

	_commentIdempotency.fillFieldMap()

	return _commentIdempotency
}

type commentIdempotency struct {
	commentIdempotencyDo commentIdempotencyDo

	ALL        field.Asterisk
	GroupID    field.String
	UserID     field.String
	RoundID    field.String
	RequestKey field.String
	Hash       field.String
	CommentID  field.String

	fieldMap map[string]field.Expr
}

func (c commentIdempotency) Table(newTableName string) *commentIdempotency {
	c.commentIdempotencyDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commentIdempotency) As(alias string) *commentIdempotency {
	c.commentIdempotencyDo.DO = *(c.commentIdempotencyDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commentIdempotency) updateTableName(table string) *commentIdempotency {
	c.ALL = field.NewAsterisk(table)
	c.GroupID = field.NewString(table, "group_id")
	c.UserID = field.NewString(table, "user_id")
	c.RoundID = field.NewString(table, "round_id")
	c.RequestKey = field.NewString(table, "request_key")
	c.Hash = field.NewString(table, "hash")
	c.CommentID = field.NewString(table, "comment_id")

	c.fillFieldMap()

	return c
}

func (c *commentIdempotency) WithContext(ctx context.Context) ICommentIdempotencyDo {
	return c.commentIdempotencyDo.WithContext(ctx)
}

func (c commentIdempotency) TableName() string { return c.commentIdempotencyDo.TableName() }

func (c commentIdempotency) Alias() string { return c.commentIdempotencyDo.Alias() }

func (c commentIdempotency) Columns(cols ...field.Expr) gen.Columns {
	return c.commentIdempotencyDo.Columns(cols...)
}

func (c *commentIdempotency) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commentIdempotency) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["group_id"] = c.GroupID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["round_id"] = c.RoundID
	c.fieldMap["request_key"] = c.RequestKey
	c.fieldMap["hash"] = c.Hash
	c.fieldMap["comment_id"] = c.CommentID
}

func (c commentIdempotency) clone(db *gorm.DB) commentIdempotency {
	c.commentIdempotencyDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commentIdempotency) replaceDB(db *gorm.DB) commentIdempotency {
	c.commentIdempotencyDo.ReplaceDB(db)
	return c
}

type commentIdempotencyDo struct{ gen.DO }

type ICommentIdempotencyDo interface {
	gen.SubQuery
	Debug() ICommentIdempotencyDo
	WithContext(ctx context.Context) ICommentIdempotencyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommentIdempotencyDo
	WriteDB() ICommentIdempotencyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommentIdempotencyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommentIdempotencyDo
	Not(conds ...gen.Condition) ICommentIdempotencyDo
	Or(conds ...gen.Condition) ICommentIdempotencyDo
	Select(conds ...field.Expr) ICommentIdempotencyDo
	Where(conds ...gen.Condition) ICommentIdempotencyDo
	Order(conds ...field.Expr) ICommentIdempotencyDo
	Distinct(cols ...field.Expr) ICommentIdempotencyDo
	Omit(cols ...field.Expr) ICommentIdempotencyDo
	Join(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo
	Group(cols ...field.Expr) ICommentIdempotencyDo
	Having(conds ...gen.Condition) ICommentIdempotencyDo
	Limit(limit int) ICommentIdempotencyDo
	Offset(offset int) ICommentIdempotencyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommentIdempotencyDo
	Unscoped() ICommentIdempotencyDo
	Create(values ...*models.CommentIdempotency) error
	CreateInBatches(values []*models.CommentIdempotency, batchSize int) error
	Save(values ...*models.CommentIdempotency) error
	First() (*models.CommentIdempotency, error)
	Take() (*models.CommentIdempotency, error)
	Last() (*models.CommentIdempotency, error)
	Find() ([]*models.CommentIdempotency, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CommentIdempotency, err error)
	FindInBatches(result *[]*models.CommentIdempotency, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CommentIdempotency) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommentIdempotencyDo
	Assign(attrs ...field.AssignExpr) ICommentIdempotencyDo
	Joins(fields ...field.RelationField) ICommentIdempotencyDo
	Preload(fields ...field.RelationField) ICommentIdempotencyDo
	FirstOrInit() (*models.CommentIdempotency, error)
	FirstOrCreate() (*models.CommentIdempotency, error)
	FindByPage(offset int, limit int) (result []*models.CommentIdempotency, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommentIdempotencyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c commentIdempotencyDo) Debug() ICommentIdempotencyDo {
	return c.withDO(c.DO.Debug())
}

func (c commentIdempotencyDo) WithContext(ctx context.Context) ICommentIdempotencyDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commentIdempotencyDo) ReadDB() ICommentIdempotencyDo {
	return c.Clauses(dbresolver.Read)
}

func (c commentIdempotencyDo) WriteDB() ICommentIdempotencyDo {
	return c.Clauses(dbresolver.Write)
}

func (c commentIdempotencyDo) Session(config *gorm.Session) ICommentIdempotencyDo {
	return c.withDO(c.DO.Session(config))
}

func (c commentIdempotencyDo) Clauses(conds ...clause.Expression) ICommentIdempotencyDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commentIdempotencyDo) Returning(value interface{}, columns ...string) ICommentIdempotencyDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commentIdempotencyDo) Not(conds ...gen.Condition) ICommentIdempotencyDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commentIdempotencyDo) Or(conds ...gen.Condition) ICommentIdempotencyDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commentIdempotencyDo) Select(conds ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commentIdempotencyDo) Where(conds ...gen.Condition) ICommentIdempotencyDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commentIdempotencyDo) Order(conds ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commentIdempotencyDo) Distinct(cols ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commentIdempotencyDo) Omit(cols ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commentIdempotencyDo) Join(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commentIdempotencyDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commentIdempotencyDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commentIdempotencyDo) Group(cols ...field.Expr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commentIdempotencyDo) Having(conds ...gen.Condition) ICommentIdempotencyDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commentIdempotencyDo) Limit(limit int) ICommentIdempotencyDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commentIdempotencyDo) Offset(offset int) ICommentIdempotencyDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commentIdempotencyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommentIdempotencyDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commentIdempotencyDo) Unscoped() ICommentIdempotencyDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commentIdempotencyDo) Create(values ...*models.CommentIdempotency) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commentIdempotencyDo) CreateInBatches(values []*models.CommentIdempotency, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commentIdempotencyDo) Save(values ...*models.CommentIdempotency) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commentIdempotencyDo) First() (*models.CommentIdempotency, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CommentIdempotency), nil
	}
}

func (c commentIdempotencyDo) Take() (*models.CommentIdempotency, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CommentIdempotency), nil
	}
}

func (c commentIdempotencyDo) Last() (*models.CommentIdempotency, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CommentIdempotency), nil
	}
}

func (c commentIdempotencyDo) Find() ([]*models.CommentIdempotency, error) {
	result, err := c.DO.Find()
	return result.([]*models.CommentIdempotency), err
}

func (c commentIdempotencyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CommentIdempotency, err error) {
	buf := make([]*models.CommentIdempotency, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commentIdempotencyDo) FindInBatches(result *[]*models.CommentIdempotency, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commentIdempotencyDo) Attrs(attrs ...field.AssignExpr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commentIdempotencyDo) Assign(attrs ...field.AssignExpr) ICommentIdempotencyDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commentIdempotencyDo) Joins(fields ...field.RelationField) ICommentIdempotencyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commentIdempotencyDo) Preload(fields ...field.RelationField) ICommentIdempotencyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commentIdempotencyDo) FirstOrInit() (*models.CommentIdempotency, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CommentIdempotency), nil
	}
}

func (c commentIdempotencyDo) FirstOrCreate() (*models.CommentIdempotency, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CommentIdempotency), nil
	}
}

func (c commentIdempotencyDo) FindByPage(offset int, limit int) (result []*models.CommentIdempotency, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commentIdempotencyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commentIdempotencyDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commentIdempotencyDo) Delete(models ...*models.CommentIdempotency) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commentIdempotencyDo) withDO(do gen.Dao) *commentIdempotencyDo {
	c.DO = *do.(*gen.DO)
	return c
}
