// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newTrial(db *gorm.DB, opts ...gen.DOOption) trial {
	_trial := trial{}

	_trial.trialDo.UseDB(db, opts...)
	_trial.trialDo.UseModel(&models.Trial{})

	tableName := _trial.trialDo.TableName()
	_trial.ALL = field.NewAsterisk(tableName)
	_trial.Hash = field.NewString(tableName, "hash")
	_trial.Expires = field.NewTime(tableName, "expires")
	_trial.Consumed = field.NewBool(tableName, "consumed")

	_trial.fillFieldMap()

	return _trial
}

type trial struct {
	trialDo trialDo

	ALL      field.Asterisk
	Hash     field.String
	Expires  field.Time
	Consumed field.Bool

	fieldMap map[string]field.Expr
}

func (t trial) Table(newTableName string) *trial {
	t.trialDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t trial) As(alias string) *trial {
	t.trialDo.DO = *(t.trialDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *trial) updateTableName(table string) *trial {
	t.ALL = field.NewAsterisk(table)
	t.Hash = field.NewString(table, "hash")
	t.Expires = field.NewTime(table, "expires")
	t.Consumed = field.NewBool(table, "consumed")

	t.fillFieldMap()

	return t
}

func (t *trial) WithContext(ctx context.Context) ITrialDo { return t.trialDo.WithContext(ctx) }

func (t trial) TableName() string { return t.trialDo.TableName() }

func (t trial) Alias() string { return t.trialDo.Alias() }

func (t trial) Columns(cols ...field.Expr) gen.Columns { return t.trialDo.Columns(cols...) }

func (t *trial) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *trial) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["hash"] = t.Hash
	t.fieldMap["expires"] = t.Expires
	t.fieldMap["consumed"] = t.Consumed
}

func (t trial) clone(db *gorm.DB) trial {
	t.trialDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t trial) replaceDB(db *gorm.DB) trial {
	t.trialDo.ReplaceDB(db)
	return t
}

type trialDo struct{ gen.DO }

type ITrialDo interface {
	gen.SubQuery
	Debug() ITrialDo
	WithContext(ctx context.Context) ITrialDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITrialDo
	WriteDB() ITrialDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITrialDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITrialDo
	Not(conds ...gen.Condition) ITrialDo
	Or(conds ...gen.Condition) ITrialDo
	Select(conds ...field.Expr) ITrialDo
	Where(conds ...gen.Condition) ITrialDo
	Order(conds ...field.Expr) ITrialDo
	Distinct(cols ...field.Expr) ITrialDo
	Omit(cols ...field.Expr) ITrialDo
	Join(table schema.Tabler, on ...field.Expr) ITrialDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITrialDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITrialDo
	Group(cols ...field.Expr) ITrialDo
	Having(conds ...gen.Condition) ITrialDo
	Limit(limit int) ITrialDo
	Offset(offset int) ITrialDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITrialDo
	Unscoped() ITrialDo
	Create(values ...*models.Trial) error
	CreateInBatches(values []*models.Trial, batchSize int) error
	Save(values ...*models.Trial) error
	First() (*models.Trial, error)
	Take() (*models.Trial, error)
	Last() (*models.Trial, error)
	Find() ([]*models.Trial, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Trial, err error)
	FindInBatches(result *[]*models.Trial, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Trial) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITrialDo
	Assign(attrs ...field.AssignExpr) ITrialDo
	Joins(fields ...field.RelationField) ITrialDo
	Preload(fields ...field.RelationField) ITrialDo
	FirstOrInit() (*models.Trial, error)
	FirstOrCreate() (*models.Trial, error)
	FindByPage(offset int, limit int) (result []*models.Trial, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITrialDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t trialDo) Debug() ITrialDo {
	return t.withDO(t.DO.Debug())
}

func (t trialDo) WithContext(ctx context.Context) ITrialDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t trialDo) ReadDB() ITrialDo {
	return t.Clauses(dbresolver.Read)
}

func (t trialDo) WriteDB() ITrialDo {
	return t.Clauses(dbresolver.Write)
}

func (t trialDo) Session(config *gorm.Session) ITrialDo {
	return t.withDO(t.DO.Session(config))
}

func (t trialDo) Clauses(conds ...clause.Expression) ITrialDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t trialDo) Returning(value interface{}, columns ...string) ITrialDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t trialDo) Not(conds ...gen.Condition) ITrialDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t trialDo) Or(conds ...gen.Condition) ITrialDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t trialDo) Select(conds ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t trialDo) Where(conds ...gen.Condition) ITrialDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t trialDo) Order(conds ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t trialDo) Distinct(cols ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t trialDo) Omit(cols ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t trialDo) Join(table schema.Tabler, on ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t trialDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITrialDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t trialDo) RightJoin(table schema.Tabler, on ...field.Expr) ITrialDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t trialDo) Group(cols ...field.Expr) ITrialDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t trialDo) Having(conds ...gen.Condition) ITrialDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t trialDo) Limit(limit int) ITrialDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t trialDo) Offset(offset int) ITrialDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t trialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITrialDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t trialDo) Unscoped() ITrialDo {
	return t.withDO(t.DO.Unscoped())
}

func (t trialDo) Create(values ...*models.Trial) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t trialDo) CreateInBatches(values []*models.Trial, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t trialDo) Save(values ...*models.Trial) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t trialDo) First() (*models.Trial, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Trial), nil
	}
}

func (t trialDo) Take() (*models.Trial, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Trial), nil
	}
}

func (t trialDo) Last() (*models.Trial, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Trial), nil
	}
}

func (t trialDo) Find() ([]*models.Trial, error) {
	result, err := t.DO.Find()
	return result.([]*models.Trial), err
}

func (t trialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Trial, err error) {
	buf := make([]*models.Trial, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t trialDo) FindInBatches(result *[]*models.Trial, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t trialDo) Attrs(attrs ...field.AssignExpr) ITrialDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t trialDo) Assign(attrs ...field.AssignExpr) ITrialDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t trialDo) Joins(fields ...field.RelationField) ITrialDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t trialDo) Preload(fields ...field.RelationField) ITrialDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t trialDo) FirstOrInit() (*models.Trial, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Trial), nil
	}
}

func (t trialDo) FirstOrCreate() (*models.Trial, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Trial), nil
	}
}

func (t trialDo) FindByPage(offset int, limit int) (result []*models.Trial, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t trialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t trialDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t trialDo) Delete(models ...*models.Trial) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *trialDo) withDO(do gen.Dao) *trialDo {
	t.DO = *do.(*gen.DO)
	return t
}
