// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newRoundShare(db *gorm.DB, opts ...gen.DOOption) roundShare {
	_roundShare := roundShare{}

	_roundShare.roundShareDo.UseDB(db, opts...)
	_roundShare.roundShareDo.UseModel(&models.RoundShare{})

	tableName := _roundShare.roundShareDo.TableName()
	_roundShare.ALL = field.NewAsterisk(tableName)
	_roundShare.RoundID = field.NewString(tableName, "round_id")
	_roundShare.GroupID = field.NewString(tableName, "group_id")
	_roundShare.TokenHash = field.NewString(tableName, "token_hash")
	_roundShare.CreatedBy = field.NewString(tableName, "created_by")
	_roundShare.CreatedAt = field.NewTime(tableName, "created_at")
	_roundShare.RevokedAt = field.NewTime(tableName, "revoked_at")

	_roundShare.fillFieldMap()

	return _roundShare
}

type roundShare struct {
	roundShareDo roundShareDo

	ALL       field.Asterisk
	RoundID   field.String
	GroupID   field.String
	TokenHash field.String
	CreatedBy field.String
	CreatedAt field.Time
	RevokedAt field.Time

	fieldMap map[string]field.Expr
}

func (r roundShare) Table(newTableName string) *roundShare {
	r.roundShareDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roundShare) As(alias string) *roundShare {
	r.roundShareDo.DO = *(r.roundShareDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roundShare) updateTableName(table string) *roundShare {
	r.ALL = field.NewAsterisk(table)
	r.RoundID = field.NewString(table, "round_id")
	r.GroupID = field.NewString(table, "group_id")
	r.TokenHash = field.NewString(table, "token_hash")
	r.CreatedBy = field.NewString(table, "created_by")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.RevokedAt = field.NewTime(table, "revoked_at")

	r.fillFieldMap()

	return r
}

func (r *roundShare) WithContext(ctx context.Context) IRoundShareDo {
	return r.roundShareDo.WithContext(ctx)
}

func (r roundShare) TableName() string { return r.roundShareDo.TableName() }

func (r roundShare) Alias() string { return r.roundShareDo.Alias() }

func (r roundShare) Columns(cols ...field.Expr) gen.Columns { return r.roundShareDo.Columns(cols...) }

func (r *roundShare) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roundShare) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["round_id"] = r.RoundID
	r.fieldMap["group_id"] = r.GroupID
	r.fieldMap["token_hash"] = r.TokenHash
	r.fieldMap["created_by"] = r.CreatedBy
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["revoked_at"] = r.RevokedAt
}

func (r roundShare) clone(db *gorm.DB) roundShare {
	r.roundShareDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roundShare) replaceDB(db *gorm.DB) roundShare {
	r.roundShareDo.ReplaceDB(db)
	return r
}

type roundShareDo struct{ gen.DO }

type IRoundShareDo interface {
	gen.SubQuery
	Debug() IRoundShareDo
	WithContext(ctx context.Context) IRoundShareDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoundShareDo
	WriteDB() IRoundShareDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoundShareDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoundShareDo
	Not(conds ...gen.Condition) IRoundShareDo
	Or(conds ...gen.Condition) IRoundShareDo
	Select(conds ...field.Expr) IRoundShareDo
	Where(conds ...gen.Condition) IRoundShareDo
	Order(conds ...field.Expr) IRoundShareDo
	Distinct(cols ...field.Expr) IRoundShareDo
	Omit(cols ...field.Expr) IRoundShareDo
	Join(table schema.Tabler, on ...field.Expr) IRoundShareDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoundShareDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoundShareDo
	Group(cols ...field.Expr) IRoundShareDo
	Having(conds ...gen.Condition) IRoundShareDo
	Limit(limit int) IRoundShareDo
	Offset(offset int) IRoundShareDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundShareDo
	Unscoped() IRoundShareDo
	Create(values ...*models.RoundShare) error
	CreateInBatches(values []*models.RoundShare, batchSize int) error
	Save(values ...*models.RoundShare) error
	First() (*models.RoundShare, error)
	Take() (*models.RoundShare, error)
	Last() (*models.RoundShare, error)
	Find() ([]*models.RoundShare, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RoundShare, err error)
	FindInBatches(result *[]*models.RoundShare, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.RoundShare) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoundShareDo
	Assign(attrs ...field.AssignExpr) IRoundShareDo
	Joins(fields ...field.RelationField) IRoundShareDo
	Preload(fields ...field.RelationField) IRoundShareDo
	FirstOrInit() (*models.RoundShare, error)
	FirstOrCreate() (*models.RoundShare, error)
	FindByPage(offset int, limit int) (result []*models.RoundShare, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoundShareDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roundShareDo) Debug() IRoundShareDo {
	return r.withDO(r.DO.Debug())
}

func (r roundShareDo) WithContext(ctx context.Context) IRoundShareDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roundShareDo) ReadDB() IRoundShareDo {
	return r.Clauses(dbresolver.Read)
}

func (r roundShareDo) WriteDB() IRoundShareDo {
	return r.Clauses(dbresolver.Write)
}

func (r roundShareDo) Session(config *gorm.Session) IRoundShareDo {
	return r.withDO(r.DO.Session(config))
}

func (r roundShareDo) Clauses(conds ...clause.Expression) IRoundShareDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roundShareDo) Returning(value interface{}, columns ...string) IRoundShareDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roundShareDo) Not(conds ...gen.Condition) IRoundShareDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roundShareDo) Or(conds ...gen.Condition) IRoundShareDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roundShareDo) Select(conds ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roundShareDo) Where(conds ...gen.Condition) IRoundShareDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roundShareDo) Order(conds ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roundShareDo) Distinct(cols ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roundShareDo) Omit(cols ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roundShareDo) Join(table schema.Tabler, on ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roundShareDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roundShareDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roundShareDo) Group(cols ...field.Expr) IRoundShareDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roundShareDo) Having(conds ...gen.Condition) IRoundShareDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roundShareDo) Limit(limit int) IRoundShareDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roundShareDo) Offset(offset int) IRoundShareDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roundShareDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundShareDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roundShareDo) Unscoped() IRoundShareDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roundShareDo) Create(values ...*models.RoundShare) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roundShareDo) CreateInBatches(values []*models.RoundShare, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roundShareDo) Save(values ...*models.RoundShare) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roundShareDo) First() (*models.RoundShare, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundShare), nil
	}
}

func (r roundShareDo) Take() (*models.RoundShare, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundShare), nil
	}
}

func (r roundShareDo) Last() (*models.RoundShare, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundShare), nil
	}
}

func (r roundShareDo) Find() ([]*models.RoundShare, error) {
	result, err := r.DO.Find()
	return result.([]*models.RoundShare), err
}

func (r roundShareDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RoundShare, err error) {
	buf := make([]*models.RoundShare, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roundShareDo) FindInBatches(result *[]*models.RoundShare, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roundShareDo) Attrs(attrs ...field.AssignExpr) IRoundShareDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roundShareDo) Assign(attrs ...field.AssignExpr) IRoundShareDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roundShareDo) Joins(fields ...field.RelationField) IRoundShareDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roundShareDo) Preload(fields ...field.RelationField) IRoundShareDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roundShareDo) FirstOrInit() (*models.RoundShare, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundShare), nil
	}
}

func (r roundShareDo) FirstOrCreate() (*models.RoundShare, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.RoundShare), nil
	}
}

func (r roundShareDo) FindByPage(offset int, limit int) (result []*models.RoundShare, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roundShareDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roundShareDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roundShareDo) Delete(models ...*models.RoundShare) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roundShareDo) withDO(do gen.Dao) *roundShareDo {
	r.DO = *do.(*gen.DO)
	return r
}
