// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newPlayer(db *gorm.DB, opts ...gen.DOOption) player {
	_player := player{}

	_player.playerDo.UseDB(db, opts...)
	_player.playerDo.UseModel(&models.Player{})

	tableName := _player.playerDo.TableName()
	_player.ALL = field.NewAsterisk(tableName)
	_player.ID = field.NewString(tableName, "id")
	_player.GroupID = field.NewString(tableName, "group_id")
	_player.Name = field.NewString(tableName, "name")
	_player.Account = field.NewString(tableName, "account")

	_player.fillFieldMap()

	return _player
}

type player struct {
	playerDo playerDo

	ALL     field.Asterisk
	ID      field.String
	GroupID field.String
	Name    field.String
	Account field.String

	fieldMap map[string]field.Expr
}

func (p player) Table(newTableName string) *player {
	p.playerDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p player) As(alias string) *player {
	p.playerDo.DO = *(p.playerDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *player) updateTableName(table string) *player {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.GroupID = field.NewString(table, "group_id")
	p.Name = field.NewString(table, "name")
	p.Account = field.NewString(table, "account")

	p.fillFieldMap()

	return p
}

func (p *player) WithContext(ctx context.Context) IPlayerDo { return p.playerDo.WithContext(ctx) }

func (p player) TableName() string { return p.playerDo.TableName() }

func (p player) Alias() string { return p.playerDo.Alias() }

func (p player) Columns(cols ...field.Expr) gen.Columns { return p.playerDo.Columns(cols...) }

func (p *player) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *player) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["id"] = p.ID
	p.fieldMap["group_id"] = p.GroupID
	p.fieldMap["name"] = p.Name
	p.fieldMap["account"] = p.Account
}

func (p player) clone(db *gorm.DB) player {
	p.playerDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p player) replaceDB(db *gorm.DB) player {
	p.playerDo.ReplaceDB(db)
	return p
}

type playerDo struct{ gen.DO }

type IPlayerDo interface {
	gen.SubQuery
	Debug() IPlayerDo
	WithContext(ctx context.Context) IPlayerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlayerDo
	WriteDB() IPlayerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlayerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlayerDo
	Not(conds ...gen.Condition) IPlayerDo
	Or(conds ...gen.Condition) IPlayerDo
	Select(conds ...field.Expr) IPlayerDo
	Where(conds ...gen.Condition) IPlayerDo
	Order(conds ...field.Expr) IPlayerDo
	Distinct(cols ...field.Expr) IPlayerDo
	Omit(cols ...field.Expr) IPlayerDo
	Join(table schema.Tabler, on ...field.Expr) IPlayerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlayerDo
	Group(cols ...field.Expr) IPlayerDo
	Having(conds ...gen.Condition) IPlayerDo
	Limit(limit int) IPlayerDo
	Offset(offset int) IPlayerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerDo
	Unscoped() IPlayerDo
	Create(values ...*models.Player) error
	CreateInBatches(values []*models.Player, batchSize int) error
	Save(values ...*models.Player) error
	First() (*models.Player, error)
	Take() (*models.Player, error)
	Last() (*models.Player, error)
	Find() ([]*models.Player, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Player, err error)
	FindInBatches(result *[]*models.Player, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Player) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlayerDo
	Assign(attrs ...field.AssignExpr) IPlayerDo
	Joins(fields ...field.RelationField) IPlayerDo
	Preload(fields ...field.RelationField) IPlayerDo
	FirstOrInit() (*models.Player, error)
	FirstOrCreate() (*models.Player, error)
	FindByPage(offset int, limit int) (result []*models.Player, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlayerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p playerDo) Debug() IPlayerDo {
	return p.withDO(p.DO.Debug())
}

func (p playerDo) WithContext(ctx context.Context) IPlayerDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p playerDo) ReadDB() IPlayerDo {
	return p.Clauses(dbresolver.Read)
}

func (p playerDo) WriteDB() IPlayerDo {
	return p.Clauses(dbresolver.Write)
}

func (p playerDo) Session(config *gorm.Session) IPlayerDo {
	return p.withDO(p.DO.Session(config))
}

func (p playerDo) Clauses(conds ...clause.Expression) IPlayerDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p playerDo) Returning(value interface{}, columns ...string) IPlayerDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p playerDo) Not(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p playerDo) Or(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p playerDo) Select(conds ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p playerDo) Where(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p playerDo) Order(conds ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p playerDo) Distinct(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p playerDo) Omit(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p playerDo) Join(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p playerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p playerDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p playerDo) Group(cols ...field.Expr) IPlayerDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p playerDo) Having(conds ...gen.Condition) IPlayerDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p playerDo) Limit(limit int) IPlayerDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p playerDo) Offset(offset int) IPlayerDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p playerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlayerDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p playerDo) Unscoped() IPlayerDo {
	return p.withDO(p.DO.Unscoped())
}

func (p playerDo) Create(values ...*models.Player) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p playerDo) CreateInBatches(values []*models.Player, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p playerDo) Save(values ...*models.Player) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p playerDo) First() (*models.Player, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Player), nil
	}
}

func (p playerDo) Take() (*models.Player, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Player), nil
	}
}

func (p playerDo) Last() (*models.Player, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Player), nil
	}
}

func (p playerDo) Find() ([]*models.Player, error) {
	result, err := p.DO.Find()
	return result.([]*models.Player), err
}

func (p playerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Player, err error) {
	buf := make([]*models.Player, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p playerDo) FindInBatches(result *[]*models.Player, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p playerDo) Attrs(attrs ...field.AssignExpr) IPlayerDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p playerDo) Assign(attrs ...field.AssignExpr) IPlayerDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p playerDo) Joins(fields ...field.RelationField) IPlayerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p playerDo) Preload(fields ...field.RelationField) IPlayerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p playerDo) FirstOrInit() (*models.Player, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Player), nil
	}
}

func (p playerDo) FirstOrCreate() (*models.Player, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Player), nil
	}
}

func (p playerDo) FindByPage(offset int, limit int) (result []*models.Player, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p playerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p playerDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p playerDo) Delete(models ...*models.Player) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *playerDo) withDO(do gen.Dao) *playerDo {
	p.DO = *do.(*gen.DO)
	return p
}
