// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newRound(db *gorm.DB, opts ...gen.DOOption) round {
	_round := round{}

	_round.roundDo.UseDB(db, opts...)
	_round.roundDo.UseModel(&models.Round{})

	tableName := _round.roundDo.TableName()
	_round.ALL = field.NewAsterisk(tableName)
	_round.ID = field.NewString(tableName, "id")
	_round.GroupID = field.NewString(tableName, "group_id")
	_round.GameID = field.NewString(tableName, "game_id")
	_round.Played = field.NewString(tableName, "played")
	_round.Version = field.NewInt(tableName, "version")
	_round.Body = field.NewBytes(tableName, "body")

	_round.fillFieldMap()

	return _round
}

type round struct {
	roundDo roundDo

	ALL     field.Asterisk
	ID      field.String
	GroupID field.String
	GameID  field.String
	Played  field.String
	Version field.Int
	Body    field.Bytes

	fieldMap map[string]field.Expr
}

func (r round) Table(newTableName string) *round {
	r.roundDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r round) As(alias string) *round {
	r.roundDo.DO = *(r.roundDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *round) updateTableName(table string) *round {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.GroupID = field.NewString(table, "group_id")
	r.GameID = field.NewString(table, "game_id")
	r.Played = field.NewString(table, "played")
	r.Version = field.NewInt(table, "version")
	r.Body = field.NewBytes(table, "body")

	r.fillFieldMap()

	return r
}

func (r *round) WithContext(ctx context.Context) IRoundDo { return r.roundDo.WithContext(ctx) }

func (r round) TableName() string { return r.roundDo.TableName() }

func (r round) Alias() string { return r.roundDo.Alias() }

func (r round) Columns(cols ...field.Expr) gen.Columns { return r.roundDo.Columns(cols...) }

func (r *round) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *round) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["group_id"] = r.GroupID
	r.fieldMap["game_id"] = r.GameID
	r.fieldMap["played"] = r.Played
	r.fieldMap["version"] = r.Version
	r.fieldMap["body"] = r.Body
}

func (r round) clone(db *gorm.DB) round {
	r.roundDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r round) replaceDB(db *gorm.DB) round {
	r.roundDo.ReplaceDB(db)
	return r
}

type roundDo struct{ gen.DO }

type IRoundDo interface {
	gen.SubQuery
	Debug() IRoundDo
	WithContext(ctx context.Context) IRoundDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoundDo
	WriteDB() IRoundDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoundDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoundDo
	Not(conds ...gen.Condition) IRoundDo
	Or(conds ...gen.Condition) IRoundDo
	Select(conds ...field.Expr) IRoundDo
	Where(conds ...gen.Condition) IRoundDo
	Order(conds ...field.Expr) IRoundDo
	Distinct(cols ...field.Expr) IRoundDo
	Omit(cols ...field.Expr) IRoundDo
	Join(table schema.Tabler, on ...field.Expr) IRoundDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoundDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoundDo
	Group(cols ...field.Expr) IRoundDo
	Having(conds ...gen.Condition) IRoundDo
	Limit(limit int) IRoundDo
	Offset(offset int) IRoundDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundDo
	Unscoped() IRoundDo
	Create(values ...*models.Round) error
	CreateInBatches(values []*models.Round, batchSize int) error
	Save(values ...*models.Round) error
	First() (*models.Round, error)
	Take() (*models.Round, error)
	Last() (*models.Round, error)
	Find() ([]*models.Round, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Round, err error)
	FindInBatches(result *[]*models.Round, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Round) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoundDo
	Assign(attrs ...field.AssignExpr) IRoundDo
	Joins(fields ...field.RelationField) IRoundDo
	Preload(fields ...field.RelationField) IRoundDo
	FirstOrInit() (*models.Round, error)
	FirstOrCreate() (*models.Round, error)
	FindByPage(offset int, limit int) (result []*models.Round, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoundDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roundDo) Debug() IRoundDo {
	return r.withDO(r.DO.Debug())
}

func (r roundDo) WithContext(ctx context.Context) IRoundDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roundDo) ReadDB() IRoundDo {
	return r.Clauses(dbresolver.Read)
}

func (r roundDo) WriteDB() IRoundDo {
	return r.Clauses(dbresolver.Write)
}

func (r roundDo) Session(config *gorm.Session) IRoundDo {
	return r.withDO(r.DO.Session(config))
}

func (r roundDo) Clauses(conds ...clause.Expression) IRoundDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roundDo) Returning(value interface{}, columns ...string) IRoundDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roundDo) Not(conds ...gen.Condition) IRoundDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roundDo) Or(conds ...gen.Condition) IRoundDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roundDo) Select(conds ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roundDo) Where(conds ...gen.Condition) IRoundDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roundDo) Order(conds ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roundDo) Distinct(cols ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roundDo) Omit(cols ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roundDo) Join(table schema.Tabler, on ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roundDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoundDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roundDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoundDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roundDo) Group(cols ...field.Expr) IRoundDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roundDo) Having(conds ...gen.Condition) IRoundDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roundDo) Limit(limit int) IRoundDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roundDo) Offset(offset int) IRoundDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roundDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoundDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roundDo) Unscoped() IRoundDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roundDo) Create(values ...*models.Round) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roundDo) CreateInBatches(values []*models.Round, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roundDo) Save(values ...*models.Round) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roundDo) First() (*models.Round, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Round), nil
	}
}

func (r roundDo) Take() (*models.Round, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Round), nil
	}
}

func (r roundDo) Last() (*models.Round, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Round), nil
	}
}

func (r roundDo) Find() ([]*models.Round, error) {
	result, err := r.DO.Find()
	return result.([]*models.Round), err
}

func (r roundDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Round, err error) {
	buf := make([]*models.Round, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roundDo) FindInBatches(result *[]*models.Round, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roundDo) Attrs(attrs ...field.AssignExpr) IRoundDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roundDo) Assign(attrs ...field.AssignExpr) IRoundDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roundDo) Joins(fields ...field.RelationField) IRoundDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roundDo) Preload(fields ...field.RelationField) IRoundDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roundDo) FirstOrInit() (*models.Round, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Round), nil
	}
}

func (r roundDo) FirstOrCreate() (*models.Round, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Round), nil
	}
}

func (r roundDo) FindByPage(offset int, limit int) (result []*models.Round, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roundDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roundDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roundDo) Delete(models ...*models.Round) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roundDo) withDO(do gen.Dao) *roundDo {
	r.DO = *do.(*gen.DO)
	return r
}
