// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newInvite(db *gorm.DB, opts ...gen.DOOption) invite {
	_invite := invite{}

	_invite.inviteDo.UseDB(db, opts...)
	_invite.inviteDo.UseModel(&models.Invite{})

	tableName := _invite.inviteDo.TableName()
	_invite.ALL = field.NewAsterisk(tableName)
	_invite.ID = field.NewString(tableName, "id")
	_invite.GroupID = field.NewString(tableName, "group_id")
	_invite.Hash = field.NewString(tableName, "hash")
	_invite.Expires = field.NewTime(tableName, "expires")
	_invite.Revoked = field.NewBool(tableName, "revoked")

	_invite.fillFieldMap()

	return _invite
}

type invite struct {
	inviteDo inviteDo

	ALL     field.Asterisk
	ID      field.String
	GroupID field.String
	Hash    field.String
	Expires field.Time
	Revoked field.Bool

	fieldMap map[string]field.Expr
}

func (i invite) Table(newTableName string) *invite {
	i.inviteDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i invite) As(alias string) *invite {
	i.inviteDo.DO = *(i.inviteDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *invite) updateTableName(table string) *invite {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.GroupID = field.NewString(table, "group_id")
	i.Hash = field.NewString(table, "hash")
	i.Expires = field.NewTime(table, "expires")
	i.Revoked = field.NewBool(table, "revoked")

	i.fillFieldMap()

	return i
}

func (i *invite) WithContext(ctx context.Context) IInviteDo { return i.inviteDo.WithContext(ctx) }

func (i invite) TableName() string { return i.inviteDo.TableName() }

func (i invite) Alias() string { return i.inviteDo.Alias() }

func (i invite) Columns(cols ...field.Expr) gen.Columns { return i.inviteDo.Columns(cols...) }

func (i *invite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *invite) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["id"] = i.ID
	i.fieldMap["group_id"] = i.GroupID
	i.fieldMap["hash"] = i.Hash
	i.fieldMap["expires"] = i.Expires
	i.fieldMap["revoked"] = i.Revoked
}

func (i invite) clone(db *gorm.DB) invite {
	i.inviteDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i invite) replaceDB(db *gorm.DB) invite {
	i.inviteDo.ReplaceDB(db)
	return i
}

type inviteDo struct{ gen.DO }

type IInviteDo interface {
	gen.SubQuery
	Debug() IInviteDo
	WithContext(ctx context.Context) IInviteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInviteDo
	WriteDB() IInviteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInviteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInviteDo
	Not(conds ...gen.Condition) IInviteDo
	Or(conds ...gen.Condition) IInviteDo
	Select(conds ...field.Expr) IInviteDo
	Where(conds ...gen.Condition) IInviteDo
	Order(conds ...field.Expr) IInviteDo
	Distinct(cols ...field.Expr) IInviteDo
	Omit(cols ...field.Expr) IInviteDo
	Join(table schema.Tabler, on ...field.Expr) IInviteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInviteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInviteDo
	Group(cols ...field.Expr) IInviteDo
	Having(conds ...gen.Condition) IInviteDo
	Limit(limit int) IInviteDo
	Offset(offset int) IInviteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInviteDo
	Unscoped() IInviteDo
	Create(values ...*models.Invite) error
	CreateInBatches(values []*models.Invite, batchSize int) error
	Save(values ...*models.Invite) error
	First() (*models.Invite, error)
	Take() (*models.Invite, error)
	Last() (*models.Invite, error)
	Find() ([]*models.Invite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Invite, err error)
	FindInBatches(result *[]*models.Invite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Invite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInviteDo
	Assign(attrs ...field.AssignExpr) IInviteDo
	Joins(fields ...field.RelationField) IInviteDo
	Preload(fields ...field.RelationField) IInviteDo
	FirstOrInit() (*models.Invite, error)
	FirstOrCreate() (*models.Invite, error)
	FindByPage(offset int, limit int) (result []*models.Invite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInviteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i inviteDo) Debug() IInviteDo {
	return i.withDO(i.DO.Debug())
}

func (i inviteDo) WithContext(ctx context.Context) IInviteDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i inviteDo) ReadDB() IInviteDo {
	return i.Clauses(dbresolver.Read)
}

func (i inviteDo) WriteDB() IInviteDo {
	return i.Clauses(dbresolver.Write)
}

func (i inviteDo) Session(config *gorm.Session) IInviteDo {
	return i.withDO(i.DO.Session(config))
}

func (i inviteDo) Clauses(conds ...clause.Expression) IInviteDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i inviteDo) Returning(value interface{}, columns ...string) IInviteDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i inviteDo) Not(conds ...gen.Condition) IInviteDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i inviteDo) Or(conds ...gen.Condition) IInviteDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i inviteDo) Select(conds ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i inviteDo) Where(conds ...gen.Condition) IInviteDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i inviteDo) Order(conds ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i inviteDo) Distinct(cols ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i inviteDo) Omit(cols ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i inviteDo) Join(table schema.Tabler, on ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i inviteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInviteDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i inviteDo) RightJoin(table schema.Tabler, on ...field.Expr) IInviteDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i inviteDo) Group(cols ...field.Expr) IInviteDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i inviteDo) Having(conds ...gen.Condition) IInviteDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i inviteDo) Limit(limit int) IInviteDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i inviteDo) Offset(offset int) IInviteDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i inviteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInviteDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i inviteDo) Unscoped() IInviteDo {
	return i.withDO(i.DO.Unscoped())
}

func (i inviteDo) Create(values ...*models.Invite) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i inviteDo) CreateInBatches(values []*models.Invite, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i inviteDo) Save(values ...*models.Invite) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i inviteDo) First() (*models.Invite, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Invite), nil
	}
}

func (i inviteDo) Take() (*models.Invite, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Invite), nil
	}
}

func (i inviteDo) Last() (*models.Invite, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Invite), nil
	}
}

func (i inviteDo) Find() ([]*models.Invite, error) {
	result, err := i.DO.Find()
	return result.([]*models.Invite), err
}

func (i inviteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Invite, err error) {
	buf := make([]*models.Invite, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i inviteDo) FindInBatches(result *[]*models.Invite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i inviteDo) Attrs(attrs ...field.AssignExpr) IInviteDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i inviteDo) Assign(attrs ...field.AssignExpr) IInviteDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i inviteDo) Joins(fields ...field.RelationField) IInviteDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i inviteDo) Preload(fields ...field.RelationField) IInviteDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i inviteDo) FirstOrInit() (*models.Invite, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Invite), nil
	}
}

func (i inviteDo) FirstOrCreate() (*models.Invite, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Invite), nil
	}
}

func (i inviteDo) FindByPage(offset int, limit int) (result []*models.Invite, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i inviteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i inviteDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i inviteDo) Delete(models ...*models.Invite) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *inviteDo) withDO(do gen.Dao) *inviteDo {
	i.DO = *do.(*gen.DO)
	return i
}
