// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newGameWish(db *gorm.DB, opts ...gen.DOOption) gameWish {
	_gameWish := gameWish{}

	_gameWish.gameWishDo.UseDB(db, opts...)
	_gameWish.gameWishDo.UseModel(&models.GameWish{})

	tableName := _gameWish.gameWishDo.TableName()
	_gameWish.ALL = field.NewAsterisk(tableName)
	_gameWish.GroupID = field.NewString(tableName, "group_id")
	_gameWish.GameID = field.NewString(tableName, "game_id")

	_gameWish.fillFieldMap()

	return _gameWish
}

type gameWish struct {
	gameWishDo gameWishDo

	ALL     field.Asterisk
	GroupID field.String
	GameID  field.String

	fieldMap map[string]field.Expr
}

func (g gameWish) Table(newTableName string) *gameWish {
	g.gameWishDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gameWish) As(alias string) *gameWish {
	g.gameWishDo.DO = *(g.gameWishDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gameWish) updateTableName(table string) *gameWish {
	g.ALL = field.NewAsterisk(table)
	g.GroupID = field.NewString(table, "group_id")
	g.GameID = field.NewString(table, "game_id")

	g.fillFieldMap()

	return g
}

func (g *gameWish) WithContext(ctx context.Context) IGameWishDo { return g.gameWishDo.WithContext(ctx) }

func (g gameWish) TableName() string { return g.gameWishDo.TableName() }

func (g gameWish) Alias() string { return g.gameWishDo.Alias() }

func (g gameWish) Columns(cols ...field.Expr) gen.Columns { return g.gameWishDo.Columns(cols...) }

func (g *gameWish) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gameWish) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 2)
	g.fieldMap["group_id"] = g.GroupID
	g.fieldMap["game_id"] = g.GameID
}

func (g gameWish) clone(db *gorm.DB) gameWish {
	g.gameWishDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gameWish) replaceDB(db *gorm.DB) gameWish {
	g.gameWishDo.ReplaceDB(db)
	return g
}

type gameWishDo struct{ gen.DO }

type IGameWishDo interface {
	gen.SubQuery
	Debug() IGameWishDo
	WithContext(ctx context.Context) IGameWishDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGameWishDo
	WriteDB() IGameWishDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGameWishDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGameWishDo
	Not(conds ...gen.Condition) IGameWishDo
	Or(conds ...gen.Condition) IGameWishDo
	Select(conds ...field.Expr) IGameWishDo
	Where(conds ...gen.Condition) IGameWishDo
	Order(conds ...field.Expr) IGameWishDo
	Distinct(cols ...field.Expr) IGameWishDo
	Omit(cols ...field.Expr) IGameWishDo
	Join(table schema.Tabler, on ...field.Expr) IGameWishDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGameWishDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGameWishDo
	Group(cols ...field.Expr) IGameWishDo
	Having(conds ...gen.Condition) IGameWishDo
	Limit(limit int) IGameWishDo
	Offset(offset int) IGameWishDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGameWishDo
	Unscoped() IGameWishDo
	Create(values ...*models.GameWish) error
	CreateInBatches(values []*models.GameWish, batchSize int) error
	Save(values ...*models.GameWish) error
	First() (*models.GameWish, error)
	Take() (*models.GameWish, error)
	Last() (*models.GameWish, error)
	Find() ([]*models.GameWish, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GameWish, err error)
	FindInBatches(result *[]*models.GameWish, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.GameWish) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGameWishDo
	Assign(attrs ...field.AssignExpr) IGameWishDo
	Joins(fields ...field.RelationField) IGameWishDo
	Preload(fields ...field.RelationField) IGameWishDo
	FirstOrInit() (*models.GameWish, error)
	FirstOrCreate() (*models.GameWish, error)
	FindByPage(offset int, limit int) (result []*models.GameWish, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGameWishDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gameWishDo) Debug() IGameWishDo {
	return g.withDO(g.DO.Debug())
}

func (g gameWishDo) WithContext(ctx context.Context) IGameWishDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gameWishDo) ReadDB() IGameWishDo {
	return g.Clauses(dbresolver.Read)
}

func (g gameWishDo) WriteDB() IGameWishDo {
	return g.Clauses(dbresolver.Write)
}

func (g gameWishDo) Session(config *gorm.Session) IGameWishDo {
	return g.withDO(g.DO.Session(config))
}

func (g gameWishDo) Clauses(conds ...clause.Expression) IGameWishDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gameWishDo) Returning(value interface{}, columns ...string) IGameWishDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gameWishDo) Not(conds ...gen.Condition) IGameWishDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gameWishDo) Or(conds ...gen.Condition) IGameWishDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gameWishDo) Select(conds ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gameWishDo) Where(conds ...gen.Condition) IGameWishDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gameWishDo) Order(conds ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gameWishDo) Distinct(cols ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gameWishDo) Omit(cols ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gameWishDo) Join(table schema.Tabler, on ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gameWishDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gameWishDo) RightJoin(table schema.Tabler, on ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gameWishDo) Group(cols ...field.Expr) IGameWishDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gameWishDo) Having(conds ...gen.Condition) IGameWishDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gameWishDo) Limit(limit int) IGameWishDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gameWishDo) Offset(offset int) IGameWishDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gameWishDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGameWishDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gameWishDo) Unscoped() IGameWishDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gameWishDo) Create(values ...*models.GameWish) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gameWishDo) CreateInBatches(values []*models.GameWish, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gameWishDo) Save(values ...*models.GameWish) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gameWishDo) First() (*models.GameWish, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GameWish), nil
	}
}

func (g gameWishDo) Take() (*models.GameWish, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GameWish), nil
	}
}

func (g gameWishDo) Last() (*models.GameWish, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GameWish), nil
	}
}

func (g gameWishDo) Find() ([]*models.GameWish, error) {
	result, err := g.DO.Find()
	return result.([]*models.GameWish), err
}

func (g gameWishDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GameWish, err error) {
	buf := make([]*models.GameWish, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gameWishDo) FindInBatches(result *[]*models.GameWish, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gameWishDo) Attrs(attrs ...field.AssignExpr) IGameWishDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gameWishDo) Assign(attrs ...field.AssignExpr) IGameWishDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gameWishDo) Joins(fields ...field.RelationField) IGameWishDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gameWishDo) Preload(fields ...field.RelationField) IGameWishDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gameWishDo) FirstOrInit() (*models.GameWish, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GameWish), nil
	}
}

func (g gameWishDo) FirstOrCreate() (*models.GameWish, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GameWish), nil
	}
}

func (g gameWishDo) FindByPage(offset int, limit int) (result []*models.GameWish, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gameWishDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gameWishDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gameWishDo) Delete(models ...*models.GameWish) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gameWishDo) withDO(do gen.Dao) *gameWishDo {
	g.DO = *do.(*gen.DO)
	return g
}
