// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/superwhys/one-more-round/internal/infra/mysql/models"
)

func newWechatAccount(db *gorm.DB, opts ...gen.DOOption) wechatAccount {
	_wechatAccount := wechatAccount{}

	_wechatAccount.wechatAccountDo.UseDB(db, opts...)
	_wechatAccount.wechatAccountDo.UseModel(&models.WechatAccount{})

	tableName := _wechatAccount.wechatAccountDo.TableName()
	_wechatAccount.ALL = field.NewAsterisk(tableName)
	_wechatAccount.AppID = field.NewString(tableName, "app_id")
	_wechatAccount.OpenIDHash = field.NewString(tableName, "openid_hash")
	_wechatAccount.UserID = field.NewString(tableName, "user_id")

	_wechatAccount.fillFieldMap()

	return _wechatAccount
}

type wechatAccount struct {
	wechatAccountDo wechatAccountDo

	ALL        field.Asterisk
	AppID      field.String
	OpenIDHash field.String
	UserID     field.String

	fieldMap map[string]field.Expr
}

func (w wechatAccount) Table(newTableName string) *wechatAccount {
	w.wechatAccountDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wechatAccount) As(alias string) *wechatAccount {
	w.wechatAccountDo.DO = *(w.wechatAccountDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wechatAccount) updateTableName(table string) *wechatAccount {
	w.ALL = field.NewAsterisk(table)
	w.AppID = field.NewString(table, "app_id")
	w.OpenIDHash = field.NewString(table, "openid_hash")
	w.UserID = field.NewString(table, "user_id")

	w.fillFieldMap()

	return w
}

func (w *wechatAccount) WithContext(ctx context.Context) IWechatAccountDo {
	return w.wechatAccountDo.WithContext(ctx)
}

func (w wechatAccount) TableName() string { return w.wechatAccountDo.TableName() }

func (w wechatAccount) Alias() string { return w.wechatAccountDo.Alias() }

func (w wechatAccount) Columns(cols ...field.Expr) gen.Columns {
	return w.wechatAccountDo.Columns(cols...)
}

func (w *wechatAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wechatAccount) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 3)
	w.fieldMap["app_id"] = w.AppID
	w.fieldMap["openid_hash"] = w.OpenIDHash
	w.fieldMap["user_id"] = w.UserID
}

func (w wechatAccount) clone(db *gorm.DB) wechatAccount {
	w.wechatAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wechatAccount) replaceDB(db *gorm.DB) wechatAccount {
	w.wechatAccountDo.ReplaceDB(db)
	return w
}

type wechatAccountDo struct{ gen.DO }

type IWechatAccountDo interface {
	gen.SubQuery
	Debug() IWechatAccountDo
	WithContext(ctx context.Context) IWechatAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWechatAccountDo
	WriteDB() IWechatAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWechatAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWechatAccountDo
	Not(conds ...gen.Condition) IWechatAccountDo
	Or(conds ...gen.Condition) IWechatAccountDo
	Select(conds ...field.Expr) IWechatAccountDo
	Where(conds ...gen.Condition) IWechatAccountDo
	Order(conds ...field.Expr) IWechatAccountDo
	Distinct(cols ...field.Expr) IWechatAccountDo
	Omit(cols ...field.Expr) IWechatAccountDo
	Join(table schema.Tabler, on ...field.Expr) IWechatAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWechatAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWechatAccountDo
	Group(cols ...field.Expr) IWechatAccountDo
	Having(conds ...gen.Condition) IWechatAccountDo
	Limit(limit int) IWechatAccountDo
	Offset(offset int) IWechatAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWechatAccountDo
	Unscoped() IWechatAccountDo
	Create(values ...*models.WechatAccount) error
	CreateInBatches(values []*models.WechatAccount, batchSize int) error
	Save(values ...*models.WechatAccount) error
	First() (*models.WechatAccount, error)
	Take() (*models.WechatAccount, error)
	Last() (*models.WechatAccount, error)
	Find() ([]*models.WechatAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WechatAccount, err error)
	FindInBatches(result *[]*models.WechatAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.WechatAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWechatAccountDo
	Assign(attrs ...field.AssignExpr) IWechatAccountDo
	Joins(fields ...field.RelationField) IWechatAccountDo
	Preload(fields ...field.RelationField) IWechatAccountDo
	FirstOrInit() (*models.WechatAccount, error)
	FirstOrCreate() (*models.WechatAccount, error)
	FindByPage(offset int, limit int) (result []*models.WechatAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWechatAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wechatAccountDo) Debug() IWechatAccountDo {
	return w.withDO(w.DO.Debug())
}

func (w wechatAccountDo) WithContext(ctx context.Context) IWechatAccountDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wechatAccountDo) ReadDB() IWechatAccountDo {
	return w.Clauses(dbresolver.Read)
}

func (w wechatAccountDo) WriteDB() IWechatAccountDo {
	return w.Clauses(dbresolver.Write)
}

func (w wechatAccountDo) Session(config *gorm.Session) IWechatAccountDo {
	return w.withDO(w.DO.Session(config))
}

func (w wechatAccountDo) Clauses(conds ...clause.Expression) IWechatAccountDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wechatAccountDo) Returning(value interface{}, columns ...string) IWechatAccountDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wechatAccountDo) Not(conds ...gen.Condition) IWechatAccountDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wechatAccountDo) Or(conds ...gen.Condition) IWechatAccountDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wechatAccountDo) Select(conds ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wechatAccountDo) Where(conds ...gen.Condition) IWechatAccountDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wechatAccountDo) Order(conds ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wechatAccountDo) Distinct(cols ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wechatAccountDo) Omit(cols ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wechatAccountDo) Join(table schema.Tabler, on ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wechatAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wechatAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wechatAccountDo) Group(cols ...field.Expr) IWechatAccountDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wechatAccountDo) Having(conds ...gen.Condition) IWechatAccountDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wechatAccountDo) Limit(limit int) IWechatAccountDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wechatAccountDo) Offset(offset int) IWechatAccountDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wechatAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWechatAccountDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wechatAccountDo) Unscoped() IWechatAccountDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wechatAccountDo) Create(values ...*models.WechatAccount) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wechatAccountDo) CreateInBatches(values []*models.WechatAccount, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wechatAccountDo) Save(values ...*models.WechatAccount) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wechatAccountDo) First() (*models.WechatAccount, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.WechatAccount), nil
	}
}

func (w wechatAccountDo) Take() (*models.WechatAccount, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.WechatAccount), nil
	}
}

func (w wechatAccountDo) Last() (*models.WechatAccount, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.WechatAccount), nil
	}
}

func (w wechatAccountDo) Find() ([]*models.WechatAccount, error) {
	result, err := w.DO.Find()
	return result.([]*models.WechatAccount), err
}

func (w wechatAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WechatAccount, err error) {
	buf := make([]*models.WechatAccount, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wechatAccountDo) FindInBatches(result *[]*models.WechatAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wechatAccountDo) Attrs(attrs ...field.AssignExpr) IWechatAccountDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wechatAccountDo) Assign(attrs ...field.AssignExpr) IWechatAccountDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wechatAccountDo) Joins(fields ...field.RelationField) IWechatAccountDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wechatAccountDo) Preload(fields ...field.RelationField) IWechatAccountDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wechatAccountDo) FirstOrInit() (*models.WechatAccount, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.WechatAccount), nil
	}
}

func (w wechatAccountDo) FirstOrCreate() (*models.WechatAccount, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.WechatAccount), nil
	}
}

func (w wechatAccountDo) FindByPage(offset int, limit int) (result []*models.WechatAccount, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wechatAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wechatAccountDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wechatAccountDo) Delete(models ...*models.WechatAccount) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wechatAccountDo) withDO(do gen.Dao) *wechatAccountDo {
	w.DO = *do.(*gen.DO)
	return w
}
