// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/code": {
            "post": {
                "description": "向目标邮箱发送登录验证码；首次注册需携带试用邀请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SendCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "使用邮箱验证码登录；新账号首次登录会消费试用邀请",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "验证码登录",
                "parameters": [
                    {
                        "description": "登录请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_User"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "撤销当前会话并清除会话 Cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/v1/groups": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "返回当前账号加入的小组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取我的小组",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-array_dto_Group"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "创建小组，创建者成为组主与首位成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "创建小组",
                "parameters": [
                    {
                        "description": "创建小组请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Group"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "返回小组成员、玩家、桌游、待确认关联与最近地点",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取小组详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Snapshot"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/bgg/search": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "外部桌游检索；授权未配置时返回明确不可用提示",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "搜索外部桌游",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/games": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "在小组内添加桌游，同组同名复用已有条目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "添加桌游",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "添加桌游请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddGameReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Game"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/invites": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "组主查看本组邀请记录，不返回明文令牌",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "获取小组邀请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-array_dto_Invite"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "组主生成七天有效的小组邀请，明文令牌仅返回一次",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "生成小组邀请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_InviteResp"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/manage": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "组主或本人执行改名、转让、移除、撤销邀请、关联与审核玩家",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "修改小组与成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "小组操作请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ManageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/photos": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "上传单张 JPEG/PNG/WebP 图片，服务端重编码后保存",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "上传照片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadPhotoResp"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/photos/{id}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "校验成员权限后返回图片，size=thumb 时返回缩略图",
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Photo"
                ],
                "summary": "读取照片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "照片 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "缩略图传 thumb",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/players": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "在小组内添加昵称玩家，重名会被拒绝",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "添加玩家",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "添加玩家请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddPlayerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Player"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/rounds": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "按日期、桌游、玩家筛选对局，返回分页结果与战绩统计",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Round"
                ],
                "summary": "获取对局列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始日期",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "桌游 ID",
                        "name": "game",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "玩家 ID",
                        "name": "player",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数，最大 100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Page"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "创建对局需携带 Idempotency-Key；修改对局需携带版本号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Round"
                ],
                "summary": "记一局或修改对局",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "对局 ID，修改时必填",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "提交标识，创建时必填",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "对局内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Round"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Round"
                        }
                    }
                }
            }
        },
        "/v1/groups/{group}/rounds/{id}": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "返回一条对局的完整内容，含版本号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Round"
                ],
                "summary": "获取对局详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "对局 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_Round"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "按版本号删除对局，版本不一致时提示刷新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Round"
                ],
                "summary": "删除对局",
                "parameters": [
                    {
                        "type": "string",
                        "description": "小组 ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "对局 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "删除对局请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteRoundReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-any"
                        }
                    }
                }
            }
        },
        "/v1/join": {
            "post": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "使用小组邀请链接中的令牌加入小组",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "加入小组",
                "parameters": [
                    {
                        "description": "加入小组请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.JoinReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-string"
                        }
                    }
                }
            }
        },
        "/v1/me": {
            "get": {
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "description": "返回当前会话对应的账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "获取当前账号",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-dto_User"
                        }
                    }
                }
            }
        },
        "/v1/status": {
            "get": {
                "description": "返回服务名、构建版本与产品阶段",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "服务健康与版本",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ginutils.Ret-api_Status"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Status": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "dto.AddGameReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.AddPlayerReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Claim": {
            "type": "object",
            "properties": {
                "player_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateGroupReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteRoundReq": {
            "type": "object",
            "properties": {
                "groupID": {
                    "type": "string"
                },
                "roundID": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "dto.Game": {
            "type": "object",
            "properties": {
                "bgg_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "original": {
                    "type": "string"
                }
            }
        },
        "dto.GameActivity": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "last_date": {
                    "type": "string"
                }
            }
        },
        "dto.Group": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "dto.Invite": {
            "type": "object",
            "properties": {
                "expires": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "revoked": {
                    "type": "boolean"
                }
            }
        },
        "dto.InviteResp": {
            "type": "object",
            "properties": {
                "expires": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.JoinReq": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.LoginReq": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ManageReq": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dto.Member": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.Page": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/dto.GameActivity"
                    }
                },
                "games": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Round"
                    }
                },
                "players": {
                    "type": "integer"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Stat"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.Player": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Round": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "minutes": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "players": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scores": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "team_score": {
                    "type": "string"
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Team"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "winners": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.SendCodeReq": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "invite": {
                    "type": "string"
                }
            }
        },
        "dto.Snapshot": {
            "type": "object",
            "properties": {
                "claims": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Claim"
                    }
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Game"
                    }
                },
                "group": {
                    "$ref": "#/definitions/dto.Group"
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Member"
                    }
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Player"
                    }
                }
            }
        },
        "dto.Stat": {
            "type": "object",
            "properties": {
                "game": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "played": {
                    "type": "integer"
                },
                "player": {
                    "type": "string"
                },
                "samples": {
                    "type": "integer"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "dto.Team": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "score": {
                    "type": "string"
                },
                "winner": {
                    "type": "boolean"
                }
            }
        },
        "dto.UploadPhotoResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "ginutils.Ret-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {}
            }
        },
        "ginutils.Ret-api_Status": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/api.Status"
                },
                "message": {}
            }
        },
        "ginutils.Ret-array_dto_Group": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Group"
                    }
                },
                "message": {}
            }
        },
        "ginutils.Ret-array_dto_Invite": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Invite"
                    }
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Game": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Game"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Group": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Group"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_InviteResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.InviteResp"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Page": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Page"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Player": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Player"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Round": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Round"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_Snapshot": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.Snapshot"
                },
                "message": {}
            }
        },
        "ginutils.Ret-dto_User": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/dto.User"
                },
                "message": {}
            }
        },
        "ginutils.Ret-string": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "message": {}
            }
        }
    },
    "securityDefinitions": {
        "SessionCookie": {
            "type": "apiKey",
            "name": "omr_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "又一局 API",
	Description:      "熟人小组对局日记的接口文档；路径相对 /api 挂载点。\n除图片读取外，所有接口返回 ginutils.Ret 包络：{code, data, message}；code 为稳定业务码，失败时 HTTP 状态同时表达语义。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
